Update README.md
trimble-oss/trimble-id-sdk-docs-for-react pull request #6
Opened 2024-12-16 11:07 UTC by meghnasamoorthy

2024-12-17 09:49 UTC, vineshparamasivam commented on README.md
> +> When you upgrade to version 1.x, storage options will no longer be available, resulting in a breaking change. For those using an older version of the SDK (i.e., <1.x), it is highly recommended to u
This looks good

2024-12-17 09:50 UTC, vineshparamasivam approved these changes, later dismissed
Changes looks good to me. APproved

2024-12-17 11:55 UTC, vasudev-j submitted a review, later dismissed

2024-12-17 11:55 UTC, vasudev-j commented on README.md
> +> As of version 1.0.0, PersistentOptions have been removed. By default, the SDK now supports in-memory token storage. Using localStorage and sessionStorage for storing sensitive information poses sev
Can we remove 'persistent storage' from the list of security risks?

2024-12-17 12:25 UTC, karthikkandasamy21 submitted a review, later dismissed

2024-12-18 06:42 UTC, vineshparamasivam approved these changes, later dismissed

2024-12-18 07:21 UTC, vineshparamasivam submitted a review, later dismissed

2024-12-18 08:04 UTC, vasudev-j requested changes

2024-12-18 08:04 UTC, vasudev-j commented on release-notes/CHANGELOG.md
> +- `PersistentOptions` have been removed. By default, the SDK now supports in-memory token storage.
Can we add that the SDK no longer supports other token storage options?

2024-12-18 08:10 UTC, meghnasamoorthy commented on release-notes/CHANGELOG.md
> +- `PersistentOptions` have been removed. By default, the SDK now supports in-memory token storage.
Done

2024-12-18 08:50 UTC, vineshparamasivam approved these changes
LGTM

2024-12-18 08:52 UTC, vasudev-j approved these changes

2024-12-18 11:26 UTC, karthikkandasamy21 approved these changes

2024-12-18 11:38 UTC, merged